[2022-05-05 13:33:18,687] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:33:14.054456+00:00 [queued]>
[2022-05-05 13:33:18,715] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:33:14.054456+00:00 [queued]>
[2022-05-05 13:33:18,716] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 13:33:18,717] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-05 13:33:18,718] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 13:33:18,880] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-05 13:33:14.054456+00:00
[2022-05-05 13:33:18,888] {standard_task_runner.py:52} INFO - Started process 85 to run task
[2022-05-05 13:33:18,897] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-05T13:33:14.054456+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmpp79mdciz', '--error-file', '/tmp/tmpjaf45gli']
[2022-05-05 13:33:18,899] {standard_task_runner.py:80} INFO - Job 47: Subtask extract
[2022-05-05 13:33:19,100] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:33:14.054456+00:00 [running]> on host 70e1e4d83c3a
[2022-05-05 13:33:19,337] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T13:33:14.054456+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-05T13:33:14.054456+00:00
[2022-05-05 13:33:19,340] {logging_mixin.py:109} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7ff0ae5226d0>
[2022-05-05 13:33:19,359] {base.py:79} INFO - Using connection to: id: mysql_db. Host: 127.0.0.1, Port: 3306, Schema: classicmodels, Login: houssem, Password: ***, extra: {}
[2022-05-05 13:33:19,376] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 60, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)")
[2022-05-05 13:33:19,414] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220505T133314, start_date=20220505T133318, end_date=20220505T133319
[2022-05-05 13:33:19,484] {standard_task_runner.py:98} ERROR - Failed to execute job 47 for task extract ((2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)"); 85)
[2022-05-05 13:33:19,511] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-05 13:33:19,770] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
