[2022-05-05 14:24:07,699] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T14:23:49.820453+00:00 [queued]>
[2022-05-05 14:24:07,724] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T14:23:49.820453+00:00 [queued]>
[2022-05-05 14:24:07,725] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 14:24:07,726] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-05 14:24:07,727] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 14:24:07,893] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-05 14:23:49.820453+00:00
[2022-05-05 14:24:07,904] {standard_task_runner.py:52} INFO - Started process 765 to run task
[2022-05-05 14:24:07,912] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-05T14:23:49.820453+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmp3bwmnaac', '--error-file', '/tmp/tmp3t5clk8t']
[2022-05-05 14:24:07,916] {standard_task_runner.py:80} INFO - Job 80: Subtask extract
[2022-05-05 14:24:08,181] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T14:23:49.820453+00:00 [running]> on host 70e1e4d83c3a
[2022-05-05 14:24:08,430] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T14:23:49.820453+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-05T14:23:49.820453+00:00
[2022-05-05 14:24:08,434] {logging_mixin.py:109} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7f5dcf039dd0>
[2022-05-05 14:24:08,463] {base.py:79} INFO - Using connection to: id: mysql_db. Host: 127.0.0.1, Port: 3306, Schema: classicmodels, Login: houssem, Password: ***, extra: {}
[2022-05-05 14:24:08,588] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 60, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)")
[2022-05-05 14:24:08,653] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220505T142349, start_date=20220505T142407, end_date=20220505T142408
[2022-05-05 14:24:09,055] {standard_task_runner.py:98} ERROR - Failed to execute job 80 for task extract ((2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)"); 765)
[2022-05-05 14:24:09,096] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-05 14:24:09,254] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
