[2022-05-11 19:17:51,780] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-11T19:17:12.996191+00:00 [queued]>
[2022-05-11 19:17:51,827] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-11T19:17:12.996191+00:00 [queued]>
[2022-05-11 19:17:51,829] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 19:17:51,830] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-11 19:17:51,831] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 19:17:52,727] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-11 19:17:12.996191+00:00
[2022-05-11 19:17:52,748] {standard_task_runner.py:52} INFO - Started process 3482 to run task
[2022-05-11 19:17:52,775] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-11T19:17:12.996191+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmpmljzf0tc', '--error-file', '/tmp/tmpkrzi4_g4']
[2022-05-11 19:17:52,779] {standard_task_runner.py:80} INFO - Job 159: Subtask extract
[2022-05-11 19:17:53,235] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-11T19:17:12.996191+00:00 [running]> on host 0b2ea813f779
[2022-05-11 19:17:54,905] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T19:17:12.996191+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-11T19:17:12.996191+00:00
[2022-05-11 19:17:54,907] {logging_mixin.py:109} INFO - done
[2022-05-11 19:17:54,908] {logging_mixin.py:109} INFO - <***.providers.postgres.hooks.postgres.PostgresHook object at 0x7f0f3cf16590>
[2022-05-11 19:17:54,929] {base.py:79} INFO - Using connection to: id: postgres_db. Host: docker.host.internal, Port: 5433, Schema: test_db, Login: postgres, Password: ***, extra: {}
[2022-05-11 19:18:05,323] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 61, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "docker.host.internal" to address: Temporary failure in name resolution

[2022-05-11 19:18:07,187] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220511T191712, start_date=20220511T191751, end_date=20220511T191807
[2022-05-11 19:18:07,614] {standard_task_runner.py:98} ERROR - Failed to execute job 159 for task extract (could not translate host name "docker.host.internal" to address: Temporary failure in name resolution
; 3482)
[2022-05-11 19:18:07,675] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-11 19:18:07,996] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
