[2022-05-05 13:17:01,613] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:16:57.756755+00:00 [queued]>
[2022-05-05 13:17:01,639] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:16:57.756755+00:00 [queued]>
[2022-05-05 13:17:01,640] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 13:17:01,641] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-05 13:17:01,642] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-05 13:17:02,933] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-05-05 13:16:57.756755+00:00
[2022-05-05 13:17:02,943] {standard_task_runner.py:52} INFO - Started process 2727 to run task
[2022-05-05 13:17:02,951] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Smart_ETL_Tool', 'extract', 'manual__2022-05-05T13:16:57.756755+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_exemple.py', '--cfg-path', '/tmp/tmpukswx6x4', '--error-file', '/tmp/tmpk7q86dds']
[2022-05-05 13:17:02,954] {standard_task_runner.py:80} INFO - Job 9: Subtask extract
[2022-05-05 13:17:03,388] {logging_mixin.py:109} INFO - Running <TaskInstance: Smart_ETL_Tool.extract manual__2022-05-05T13:16:57.756755+00:00 [running]> on host 70e1e4d83c3a
[2022-05-05 13:17:03,818] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Smart_ETL_Tool
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T13:16:57.756755+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-05T13:16:57.756755+00:00
[2022-05-05 13:17:03,820] {logging_mixin.py:109} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7fe70b70d310>
[2022-05-05 13:17:03,833] {base.py:79} INFO - Using connection to: id: mysql_db. Host: localhost, Port: 3306, Schema: classicmodels, Login: houssem, Password: ***, extra: {}
[2022-05-05 13:17:03,845] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_exemple.py", line 60, in extract
    df = hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 137, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
[2022-05-05 13:17:03,868] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=Smart_ETL_Tool, task_id=extract, execution_date=20220505T131657, start_date=20220505T131701, end_date=20220505T131703
[2022-05-05 13:17:03,934] {standard_task_runner.py:98} ERROR - Failed to execute job 9 for task extract ((2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"); 2727)
[2022-05-05 13:17:03,975] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-05 13:17:04,046] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
